spring.application.name=gestaohospedes

spring.datasource.url=jdbc:postgresql://localhost:5432/gestaohospedes_db
#${POSTGRES_DB}

spring.datasource.username=admin
#${POSTGRES_USER}

spring.datasource.password=senha_gestao
#${POSTGRES_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

app.jwt.chave-secreta=c4R9mP7xL2sQ8nV5eT1aK6zW0bH3yF9jUqM4rX8pD2nL7cS1
app.jwt.minutos-de-validade=120
